checks:
  javascript: true
build:
  environment:
    node: '8.4.0'
  tests:
    override:
      - scss-lint-run
filter:
    paths:
      - "app/*"
      - "config/*"
      - "private/js/*"
      - "util/*"
    excluded_paths:
      - "private/js/plugins/*"
