language: node_js

os:
  - linux
  - osx

node_js:
  - '6'
  - '7'
  - '8.4'
  - 'stable'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y g++ build-essential
  - gem install compass scss_lint
  - npm install coveralls grunt-cli jshint marked coffee-script -g

cache:
  bundler: true
  directories:
  - node_modules

env:
  - NODE_ENV=development
  - S3_BUCKET=andrelademann-testing
