language: node_js

node_js:
  - 'stable'

before_install:
  - apt-get -qq update
  - apt-get install -y g++ build-essential
  - gem update
  - gem install compass scss_lint
  - rvm install 2.2.2
  - npm install coveralls grunt-cli eslint marked node-gyp -g

cache:
  bundler: true
  directories:
  - node_modules
