language: node_js

node_js:
  - 'stable'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y g++ build-essential
  - sudo rvm install 2.2.2
  - sudo gem update
  - sudo gem install compass scss_lint
  - sudo npm install coveralls grunt-cli eslint marked node-gyp -g

cache:
  bundler: true
  directories:
  - node_modules
