language:
 - node_js
 - ruby-head

node_js:
  - 'stable'

before_script:
  - npm install coveralls grunt-cli eslint -g
  - gem install scss_lint


cache:
  bundler: true
  directories:
  - node_modules
