language: node_js

node_js:
  - 'stable'

before_script:
  - gem update
  - gem install compass scss_lint
  - rvm install 2.2.2
  - npm install coveralls grunt-cli eslint marked node-gyp -g

cache:
  bundler: true
  directories:
  - node_modules
