language: node_js

node_js:
  - 'stable'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y g++ build-essential
  - gem install compass scss_lint
  - npm install coveralls grunt-cli eslint marked -g

cache:
  bundler: true
  directories:
  - node_modules
