language: node_js

node_js:
  - 'stable'

before_script:
  - rvm install 2.2.2
  - npm install coveralls grunt-cli eslint -g
  - gem install scss_lint

install:
  - make npm
  - make bundler

cache:
  bundler: true
  directories:
  - node_modules
