version: '3.5'
services:
    app:
<<<<<<< HEAD
        image: vergissberlin/andrelademann-de
=======
        image: vergissberlin/andrelademann
>>>>>>> Added docker-compose file for production environment
        environment:
          - AUTH_SECRET
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_REGION
          - BASE_USER
          - BASE_SECRET
          - BUGSNAG_TOKEN
          - MONGO_DATA_DIR=/data/db
          - MONGODB_URI
          - NODE_ENV
          - NODE_SECRET
          - S3_BUCKET
<<<<<<< HEAD
          - VIRTUAL_HOST=${DOMAINS}
          - VIRTUAL_NETWORK=${NETWORK}
          - LETSENCRYPT_HOST=${DOMAINS}
          - LETSENCRYPT_EMAIL=info@andrelademann.de
=======
        environment:
          VIRTUAL_HOST: ${DOMAINS}
          VIRTUAL_NETWORK: ${NETWORK}
          VIRTUAL_PORT: 3232
          LETSENCRYPT_HOST: ${DOMAINS}
          LETSENCRYPT_EMAIL: info@andrelademann.de
>>>>>>> Added docker-compose file for production environment
        links:
          - mongodb:mongodb
        working_dir: /var/app
        command: npm start
    mongodb:
        image: mongo:latest
        environment:
<<<<<<< HEAD
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_INITDB_ROOT_USERNAME
          - MONGO_INITDB_ROOT_PASSWORD
          - MONGO_INITDB_DATABASE
        volumes:
            - ./data/db:/data/db
            - ./data/backup:/data/backup
        ports:
          - 2727:27017
=======
          MONGO_DATA_DIR: /data/db
          MONGO_LOG_DIR: /dev/null
          MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
          MONGO_INITDB_DATABASE:  ${MONGODB_DB}
        volumes:
            - ./data/db:/data/db
            - ./data/backup:/data/backup
>>>>>>> Added docker-compose file for production environment
        command: mongod --smallfiles --logpath=/dev/null
networks:
  default:
    external:
      name: ${NETWORK}
