version: '3'
services:
    nodejs:
        image: node
        environment:
          - MONGO_DATA_DIR=/data/db
          - NODE_ENV=development
          - AWS_ACCESS_KEY_ID=foo
          - AWS_SECRET_ACCESS_KEY=foo
          - S3_BUCKET=foo
        volumes:
          - ./app:/var/www/app
          - ./config:/var/www/config
        ports:
          - "3000:3000"
        links:
          - mongodb:mongodb
    mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
            - ./data/backup:/data/backup
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
