version: '3.5'
services:
    app:
        image: vergissberlin:andrelademann
        build: .
        environment:
          - AUTH_SECRET=moo
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_REGION
          - BASE_USER
          - BASE_SECRET
          - BUGSNAG_TOKEN
          - MONGO_DATA_DIR=/data/db
          - MONGODB_URI=mongodb://ala:ala@mongodb:27017/admin
          - NODE_ENV
          - NODE_SECRET
          - S3_BUCKET
        volumes:
          - ./:/var/app
        ports:
          - 3232:3232
        links:
          - mongodb:mongodb
        working_dir: /var/app
        command: npm start
    mongodb:
        image: mongo:latest
        environment:
          MONGO_DATA_DIR: /data/db
          MONGO_LOG_DIR: /dev/null
          MONGO_INITDB_ROOT_USERNAME: ala
          MONGO_INITDB_ROOT_PASSWORD: ala
          MONGO_INITDB_DATABASE: ala
        volumes:
            - ./data/db:/data/db
            - ./data/backup:/data/backup
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null
