version: '3.5'

services:
    app:
        environment:
          - LETSENCRYPT_HOST=${DOMAINS}
          - LETSENCRYPT_EMAIL=info@andrelademann.de
          - NODE_ENV=production
          - VIRTUAL_HOST=${DOMAINS}
          - VIRTUAL_NETWORK=${NETWORK}
          - VIRTUAL_PORT=${PORT}
        restart: on-failure
    mongodb:
        restart: on-failure
